export const PKG_PREFIX = '@element-plus-next'
export const PKG_NAME = 'element-plus-next'
export const PKG_CAMELCASE_NAME = 'ElementPlusNext'
export const PKG_CAMELCASE_LOCAL_NAME = 'ElementPlusNextLocale'
export const PKG_BRAND_NAME = 'Element Plus Next'
