blank_issues_enabled: false
contact_links:
  - name: Create new issue
    url: https://issue.element-plus.org/
    about: The issue which is not created via https://issue.element-plus.org/ will be closed immediately.
