# This workflow runs on target, so there is no need to worry about secrets

name: 🧪 Test SSR

on: pull_request

jobs:
  # Build successfully, start deployment
  test:
    name: SSR rendering test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Local build
        run: pnpm build
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Do test
        run: pnpm test:ssr
