# Unit Test Coverage Report

name: 🧪 Test Coverage

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Coverage (${{ matrix.node-name }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16']
        include:
          - node-version: '16'
            node-name: 'Latest'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add dev branch
        run: git branch dev origin/dev
      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-step: install
          test-script: pnpm run test:coverage
